# After registering a name on build.snapcraft.io, commit an uncommented line:
name: terrarium
version: '0.0.1'
summary: IoT Hub for monitoring Hydroponics
description: |
  Snap to be deployed on a Raspberry Pi with a variety of sensors to monitor
  and record data related to Hydroponics setups.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  terrarium:
    command: test.py

parts:
  setup:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    source: .
  